" This one is for pathogen
execute pathogen#infect()
filetype plugin indent on

"" Enable syntax highlighting
syntax enable 

" Set color scheme
set background=dark
colorscheme solarized

" Change tabs to 2 spaces
set expandtab
set softtabstop=2

" Add line numbers
set number
set relativenumber
" set cursorline " solarized colorscheme does not support this.
:hi CursorLine cterm=NONE ctermbg=darkblue ctermfg=white guibg=darkblue ctermfg=white

" Automatically indent when starting new lines in code blocks
set autoindent

" shows column, & line number in bottom right
set ruler

" Searching
set incsearch
set hlsearch

" Move vertically by visual line
nnoremap j gj
nnoremap k gk
nnoremap B ^
nnoremap E $
nnoremap $ <nop>
nnoremap ^ <nop>
